baseurl = ""
title = "Rahul Alokkan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[params]
  author = "Rahul Alokkan"
  info = "Community Lead"
  description = "RA7's landing page"
  keywords = "landing,personal.developer"
  avatarurl = "images/avatar.jpg"
  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"
  colorScheme = "auto"
  hidecolorschemetoggle = false

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Rahul-Alokkan/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/rahul-alokkan-16384b196/"